[package]
name = "sorting"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
fast-float = "0.2.0"
inquire = "0.7.5"
lexical = "7.0.4"
memchr = "2.7.4"
memmap2 = "0.9.5"
rayon = "1.10.0"
smallstr = "0.3.0"
